### ISSUE TITLE
10. notification 트리거 시간 설정

### ISSUE THREAD

**Issue by smc219** [ProjectInTheClass/NaggingScheduler#10]
스케쥴의 시간보다 긴 시간 동안 울리지는 않도록 한다.

**Comment by smc219** [comment]
스케쥴의 시간보다 긴 시간 동안 울리지 않는건 이제 어떻게 할 수 있을 것 같은데, 이걸 어떤 방식으로 repeat 할 수 있을지에 대해서는 다시한번 생각해보아야할 것 같음

**Comment by ape0108792** [comment]
이슈 정리!
